version: "3.7"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.8
    environment:
      discovery.type: single-node
    container_name: elasticsearch
    tmpfs:
      - /usr/share/elasticsearch/data/
    ports:
      - "9200:9200"

  redis:
    container_name: redis
    image: redis:5-alpine
    tmpfs:
      - /data
    ports:
      - "6379:6379"
